### ISSUE TITLE
kong ingress controller helm chart overwrite values to subcharts now working 0.12.0

### ISSUE THREAD

**Issue by tkcontiant** [Kong/charts#1037]
Hello, I am using the latest version of KONG ingress controller.

I am trying to use it with AWS EKS + NLB + ACM Certificate via annotation in proxy.

steps to reproduce:

helm upgrade --install  kong-public . -f values.yaml -n kong --create-namespace

The initial installation will create Class LoadBalancer therefore I need NLB so I am using these values.yaml
After that, you will notice that annotations are not used nor nameOverride in the final template.

Also second BUG: Without this is almost not possible to test the chart

```
helm template kong . -n kong > out
Error: template: kong-ingress/templates/tests/test-resources.yaml:1:15: executing "kong-ingress/templates/tests/test-resources.yaml" at <.Values.deployment.test.enabled>: nil pointer evaluating interface {}.test
```

```
deployment:
  test:
    enabled: false

controller:
  proxy:
    nameOverride: "{{ .Release.Name }}-gateway-proxy"
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "*"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:XXXXXX"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "kong-proxy-tls"
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-internal: "false"
      # service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
    http:
      enabled: true
      servicePort: 80
      containerPort: 8000
    tls:
      enabled: true
      servicePort: 443
      containerPort: 8443
      overrideServiceTargetPort: 8000
  enabled: true

  deployment:
    kong:
      enabled: false

  ingressController:
    ingressClass: kong-public
    enabled: true
```

This is how the helm chart structure look's like
```
.
├── charts
│   └── kong
│       ├── charts
│       ├── ci
│       ├── crds
│       ├── example-values
│       └── templates
├── ci
│   └── __snapshots__
├── example-values
└── templates
    └── tests
```
