### ISSUE TITLE
not able to enable service monitor in kong/ingress

### ISSUE THREAD

**Issue by jjiang10-sv** [Kong/charts#1160]
in the kong/ingress chart, if I enable the service monitor , then gateway-proxy loadbalance will get error of no reponse from server.
Could I know how to enable the service monitor in EKS?
ingress/values.yaml

![image](https://github.com/user-attachments/assets/d394cdb3-191f-4f81-9d3e-f19423b5887d)

john@johnjiangs-MacBook-Pro ~ % curl -i a61cb6ce144434571b0f235c088da672-319685901.us-west-1.elb.amazonaws.com
curl: (52) Empty reply from server

**Comment by pmalek** [comment]
`ServiceMonitor` is a [Prometheus operator CRD](https://github.com/prometheus-operator/prometheus-operator/tree/main?tab=readme-ov-file#customresourcedefinitions) which defines which `Service`s are monitored using the Prometheus operator.

It shouldn't affect anything related to connectivity of the LB.

Can you provide more information on this issue? LB `Service` manifest with and without said `serviceMonitor` values set?

**Comment by tanoggy** [comment]
hi @jjiang10-sv 
because kong-ingress inherit from kong
you can enable from value file with config
```
controller:
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus # Edit this


gateway:
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus # Edit this
```
