### ISSUE TITLE
no imagePullSecrets of ingressController part support in values.yaml

### ISSUE THREAD

**Issue by songhd** [Kong/charts#1162]
in the values.yaml of helm chart, the pullSecrets and pullPolicy statement doesn't work in ingressController part, but works for kong-gateway

for example 

```yaml
#kong-gateway works
image:
  repository: private-repo/kong
  tag: "3.7"
  pullPolicy: "Always"
  pullSecrets: ["***"]

#ingress controller not work
ingressController:
  enabled: true
  image:
    repository: private-repo/kubernetes-ingress-controller
    tag: "3.3"
    pullPolicy: "Always"
    pullSecrets: ["***"]
```
