### ISSUE TITLE
coulld not set mtls to gateway

### ISSUE THREAD

**Issue by rookie-fpc** [Kong/charts#1189]
gateway.yaml
```
admin:
  enabled: true
  type: ClusterIP
  ClusterIP: None
  annotations: {}
  labels: {}

  http:
    enabled: false

  tls:
    enabled: true
    servicePort: 8444
    containerPort: 8444
    parameters:
    - http2
    client:
      caBundle: ""
      secretName: "admin-api-ca-cert"
```

get secret
```
[root@iadlnespto2 kong]# kubectl get secret -n kong
NAME                                                    TYPE                DATA   AGE
admin-api-ca-cert                                       kubernetes.io/tls   2      3h56m
```

test helm:
```
[root@iadlnespto2 kong]# helm install kong -n kong  . -f vales1.yaml --dry-run --debug
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/.kube/config
install.go:224: 2024-12-05 15:17:07.091094053 +0800 CST m=+0.030684324 [debug] Original chart version: ""
install.go:241: 2024-12-05 15:17:07.091141774 +0800 CST m=+0.030732042 [debug] CHART PATH: /home/online/kong

install.go:263: 2024-12-05 15:17:07.108286707 +0800 CST m=+0.047876978 [debug] WARNING: This chart or one of its subcharts contains CRDs. Rendering may fail or contain inaccuracies.
Error: INSTALLATION FAILED: execution error at (kong/templates/service-kong-admin.yaml:95:4): kong/admin-api-ca-cert secret not found
helm.go:86: 2024-12-05 15:17:07.123929914 +0800 CST m=+0.063520181 [debug] execution error at (kong/templates/service-kong-admin.yaml:95:4): kong/admin-api-ca-cert secret not found
INSTALLATION FAILED
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:158
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.8.1/command.go:985
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.8.1/command.go:1041
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:85
runtime.main
        runtime/proc.go:271
runtime.goexit
        runtime/asm_amd64.s:1695
```

why I get this error
