### ISSUE TITLE
Kong control plane cannot start

### ISSUE THREAD

**Issue by SeungyeopShin** [Kong/charts#1198]
Hi.
I'm trying to deploy kong(CE) chart in hybrid mode as https://docs.konghq.com/gateway/latest/install/kubernetes/proxy/.
However, `wait-for-db` container in `kong-cp` pod fails with following error.

```bash
Error:
/usr/local/share/lua/5.1/kong/cmd/start.lua:127: Kong is already running in /tmp/tmp.8hhyJ6IRXR
stack traceback:
[C]: in function 'assert'
/usr/local/share/lua/5.1/kong/cmd/start.lua:127: in function 'cmd_exec'
/usr/local/share/lua/5.1/kong/cmd/init.lua:38: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:38>
[C]: in function 'xpcall'
/usr/local/share/lua/5.1/kong/cmd/init.lua:38: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:22>
(command line -e):5: in function 'inline_gen'
init_worker_by_lua(nginx.conf:199):44: in function <init_worker_by_lua(nginx.conf:199):43>
[C]: in function 'xpcall'
init_worker_by_lua(nginx.conf:199):52: in function <init_worker_by_lua(nginx.conf:199):50>
```
Is there any way to resolve this error?

**Install Information**
- k8s(AWS EKS) version : 1.30
- namespace : kong-test
- values-cp.yaml
```yaml
# Do not use Kong Ingress Controller
ingressController:
  enabled: false
   
image:
  repository: kong/kong-gateway
  tag: "3.9.0.0"
   
# Mount the secret created earlier
secretVolumes:
  - kong-cluster-cert
   
env:
  # This is a control_plane node
  role: control_plane
  # These certificates are used for control plane / data plane communication
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
   
  # Database
  # CHANGE THESE VALUES
  database: postgres
  pg_database: kong
  pg_user: kong
  pg_password: demo123
  pg_host: kong-cp-postgresql.kong-test.svc.cluster.local
  pg_ssl: "on"
   
  # Kong Manager password
  password: kong_admin_password
   
# The control plane serves the Admin API
admin:
  enabled: true
  http:
    enabled: true
   
# Clustering endpoints are required in hybrid mode
cluster:
  enabled: true
  tls:
    enabled: true
   
clustertelemetry:
  enabled: true
  tls:
    enabled: true
   
# Optional features
manager:
  enabled: false
   
# These roles will be served by different Helm releases
proxy:
  enabled: false

# This is for testing purposes only
# DO NOT DO THIS IN PRODUCTION
# Your cluster needs a way to create PersistentVolumeClaims
# if this option is enabled
postgresql:
  enabled: true
  auth:
    password: demo123  
```

- used helm cli : helm upgrade -i kong-cp kong/kong -f ./values-cp.yaml -n kong-test
