### ISSUE TITLE
Migration jobs fail when in Hybrid mode

### ISSUE THREAD

**Issue by ego93** [Kong/charts#1209]
I have an existing setup, I've enabled certificates in my helm vales and when I deploy the `pre-upgrade-migrations` container fails with `Error: cluster certificate and key must be provided to use Hybrid mode`

```
migrations:
  enabled: true
  preUpgrade: true
  postUpgrade: true

certificates:
  enabled: true
  admin:
    enabled: true
    commonName: "kong-admin"

  cluster:
    enabled: true
    commonName: "kong-cluster"
```
