### ISSUE TITLE
autoscaling enabled is broken in current chart.

### ISSUE THREAD

**Issue by btkelly** [Kong/charts#122]
With the following values provided for auto scaling I receive the following error when attempting to deploy to Google Kuberentes Engine running the latest version. If I disable autoscaling everything works fine but I would like to have this feature enabled.

**Values Yaml:**
```yaml
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
```

**GKE Error:**
> Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta2"
