### ISSUE TITLE
certificates not applying to migrations jobs in hybird mode

### ISSUE THREAD

**Issue by ego93** [Kong/charts#1241]
When I configure certificates in the helm values and apply the upgrade migrations jobs fail with `Error: cluster certificate and key must be provided to use Hybrid mode`

Helm values:
```yaml
certificates:
  enabled: true
  proxy:
    enabled: false
  portal:
    enabled: false
  admin:
    enabled: false
  cluster:
    enabled: true
    commonName: "kong_clustering"

migrations:
  preUpgrade: true
  postUpgrade: true
```

Kong chart `2.46.0`

I would expect the auto-set environment variables to be applied to the migration jobs too
https://github.com/Kong/charts/blob/36a457c61effa4623fe146b06fb58afb95f6ea55/charts/kong/templates/_helpers.tpl#L1022
