### ISSUE TITLE
Issue with admission webhook while validating "unique" key in secrets

### ISSUE THREAD

**Issue by darkxeno** [Kong/charts#1245]
While using this config for the kong helm chart:

```
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: networking
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "3"
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
      - chart: kong
        repoURL: 'https://charts.konghq.com'
        targetRevision: 2.46.0
        helm:
          parameters:
          - name: env.trusted_ips
            value: ${var.vpc_cidr}
          - name: service.beta.kubernetes.io/aws-load-balancer-name
            value: ${var.cloud_config.env}-xxx-k8s-loadbalancer
          values: |
            ingressController:
              admissionWebhook:
                enabled: true
                filterSecrets: true
              env:
                feature_gates: GatewayAlpha=true,RewriteURIs=true,CombinedServicesFromDifferentHTTPRoutes=true
...
```

I am facing errors like these (from the kong logs):
```
2025-02-04T18:26:45Z	info	admission-server	Object admission request not allowed	{"v": 0, "name": "auth0-consumer-secret", "kind": "Secret", "namespace": "networking", "message": "consumer credential failed validation: unique key constraint violated for key"}
2025-02-04T18:26:45Z	info	admission-server	Object admission request not allowed	{"v": 0, "name": "grafana-key-auth-consumer-secret", "kind": "Secret", "namespace": "grafana", "message": "consumer credential failed validation: unique key constraint violated for key"}
```

I know the key field of each of these secrets need to be unique, so i decided to use `filterSecrets: true` config with the label `konghq.com/validate: "true"` on the secrets to narrow down the conflicting secrets.

If i filter all secrets with that annotation in the whole cluster, i get these too as the unique ones.
```
k get secrets --all-namespaces -l "konghq.com/validate=true"
NAMESPACE    NAME                               TYPE     DATA   AGE
grafana      grafana-key-auth-consumer-secret   Opaque   2      5h44m
networking   auth0-consumer-secret              Opaque   5      5h52m
```

But still each time i try to sync on argocd i get the following errors again:

```
one or more objects failed to apply, reason: error when patching "/dev/shm/2190820843": admission webhook "secrets.credentials.validation.ingress-controller.konghq.com" denied the request: consumer credential failed validation: unique key constraint violated for key,error when patching "/dev/shm/1637693030": admission webhook "secrets.plugins.validation.ingress-controller.konghq.com" denied the request: consumer credential failed validation: unique key constraint violated for key
```

Any idea what can be the problem here? i am using kong on the dbless mode.

Thank you so much
