### ISSUE TITLE
Proxy service don't subtitute vales from values. yaml

### ISSUE THREAD

**Issue by santosh0705** [Kong/charts#1260]
I tried deploying KIC with below values.yaml but the proxy server still created with port 80.

values.yaml
```
controller:
  proxy:
    http:
      enabled: false
    tls:
      enabled: true
```

kong-gateway-proxy service
```
spec:
  ports:
  - name: kong-proxy
    nodePort: 31566
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: kong-proxy-tls
    nodePort: 31352
    port: 443
    protocol: TCP
    targetPort: 8443
  type: LoadBalancer
```

However If I get the values from the helm release (helm get values kong -n kong -a) I see the correct values in it:
```
COMPUTED VALUES:
controller:
  proxy:
    annotations: {}
    enabled: true
    http:
      containerPort: 8000
      enabled: false
      parameters: []
      servicePort: 80
    ingress:
      annotations: {}
      enabled: false
      hostname: null
      hosts: []
      ingressClassName: null
      labels: {}
      path: /
      pathType: ImplementationSpecific
    labels:
      enable-metrics: "true"
    loadBalancerClass: ""
    loadBalancerSourceRanges: []
    nameOverride: '{{ .Release.Name }}-gateway-proxy'
    stream: []
    tls:
      appProtocol: ""
      containerPort: 8443
      enabled: true
      parameters:
      - http2
      servicePort: 443
    type: LoadBalancer
```

**Comment by pmalek** [comment]
To configure the Gateway you need to use the [`gateway` section](https://github.com/Kong/charts/blob/1308d1d2600056aa9dbb2f28635dd4c2cbc44873/charts/ingress/values.yaml#L30-L46) of the `values.yaml` (assuming you use the `ingress` chart).

```
gateway:
  proxy:
    http:
      enabled: false
    tls:
      enabled: true
```
