### ISSUE TITLE
[kong] not able to pass the kong.yaml file path in values.yaml

### ISSUE THREAD

**Issue by imashwani** [Kong/charts#1301]
Hi,

I am using kong with dbless and using a declarative file for the config. I want to pass the kong config file path as the parameter in values.yaml. 

In the below example, I am not able to understand how to pass the file path, so that the kong config (service and routes) is segregated from helm file.

```
dblessConfig:
  # Either Kong's configuration is managed from an existing ConfigMap (with Key: kong.yml)
  configMap: ""
  # Or Kong's configuration is managed from an existing Secret (with Key: kong.yml)
  secret: ""
  # Or the configuration is passed in full-text below
  config: |
  # # _format_version: "1.1"
  # # services:
  # #   # Example configuration
  # #   # - name: example.com
  # #   #   url: http://example.com
  # #   #   routes:
  # #   #   - name: example
  # #   #     paths:
  # #   #     - "/example"
```

in the config-dbless.yaml, it seems to be taking the value passed in the config, and not taking the file data.

```
{{- if .Values.deployment.kong.enabled }}
{{- if (and (not .Values.ingressController.enabled) (eq .Values.env.database "off")) }}
{{- if not (or .Values.dblessConfig.configMap .Values.dblessConfig.secret) }}
{{- if .Values.dblessConfig.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kong.dblessConfig.fullname" . }}
  namespace: {{ template "kong.namespace" . }}
  labels:
    {{- include "kong.metaLabels" . | nindent 4 }}
data:
  kong.yml: | {{- .Values.dblessConfig.config | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
```

There is an option to pass the filepath using --sert-file while running helm install, but I don't want to do that and use the values.yaml self sufficient. How can I achieve this?

**Comment by pmalek** [comment]
You should be able to get that working by just uncommenting the example config:

```yaml
dblessConfig:
  config: |
    _format_version: "1.1"
    services:
      - name: example.com
        url: http://example.com
        routes:
        - name: example
          paths:
          - "/example"
```
