### ISSUE TITLE
Support `pullSecrets` for ingress controller in `ingress` chart

### ISSUE THREAD

**Issue by pmalek** [Kong/charts#1318]
### Problem statement

`kong` chart (base for `ingress`) supports setting the `pullSecrets` via `image.pullSecrets`.

In order to make this work for the ingress controller deployment, deployed in a separate subchart users have to define the image pull secrets in a separate subtree:

```
controller:
  image:
    pullSecrets:
      - myrepo-regcred
  ingressController:
    image:
      repository: myrepo
      tag: "3.4.5"
```

This task tracks the implementation of support for image pull secrets under the `ingressController` key.

### Additional notes

This will require work on both `kong` and `ingress` charts.

The former will require some additional logic as the pull secrets are considered a pod wide setting so the ingress controller pull secrets should only work when we the values provided result in ingress controller only deployment.

#FTI-6694
