### ISSUE TITLE
Start two kong charts in different namespace will affect each other?

### ISSUE THREAD

**Issue by NICK-DUAN** [Kong/charts#176]
Here is my problem:

I installed two kong charts in my cluster. For example, the kong in namespace `nick-kong` has custom plugin: plugin-A, plugin-B, the kong in namespace `test-kong` has custom plugin: plugin-C.
And when I create a `KongPlugin` with plugin C in namespace `test-kong`, I have a error: 
```shell
Error: Internal error occurred: failed calling webhook "validations.kong.konghq.com": Post https://test-kong-kong-validation-webhook.test-kong.svc:443/?timeout=30s: dial tcp 10.96.181.151:443: connect: connection refused
helm.go:94: [debug] Internal error occurred: failed calling webhook "validations.kong.konghq.com": Post https://test-kong-kong-validation-webhook.test-kong.svc:443/?timeout=30s: dial tcp 10.96.181.151:443: connect: connection refused
```
here is the order of execution of commands:
```shell
# namespace nick-kong, has custom plugin: plugin-A, plugin-B
helm3 dependency update ./charts/kong/
helm3 install nick-kong./charts/kong/ -f ./config/helm_config/testing.yaml --namespace nick-kong --debug --create-namespace --set ingressController.installCRDs=false
kubectl wait --for=condition=available --timeout=600s deployment/$nick-kong-kong -n nick-kong


# namespace test-kong, has custom plugin: plugin-C
helm3 dependency update ./charts/kong/
helm3 install test-kong./charts/kong/ -f ./config/helm_config/testing.yaml --namespace test-kong --debug --create-namespace --set ingressController.installCRDs=false
kubectl wait --for=condition=available --timeout=600s deployment/$test-kong-kong -n test-kong

# now create a CRD resource KongPlugin with plugin-C in namespace test-kong
helm3 install test-kong-config ./coding-kong-config -f coding-kong-config/config/testing.yaml --namespace test-kong --debug
```

This is the yaml file finally generated by `test-kong-config charts`
```
apiVersion: v1
kind: Service
metadata:
  name: test-svc
spec:
  type: ExternalName
  externalName: nick.test.com
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: plugin-c
plugin: test-plugin
config:
  auth_token: 7dlda637-as7e-4377-asdb-4943ssd6e73f
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata: 
  name: test-ing
  annotations:
    plugins.konghq.com: plugin-c
spec:
  rules:
  - http:
      paths:
      - path: /api/name
        backend: 
          serviceName: test-svc
          servicePort: 80
```

When I helm install  or apply yaml file directly, it returned:
```shell
Error: Internal error occurred: failed calling webhook "validations.kong.konghq.com": Post https://test-kong-kong-validation-webhook.test-kong.svc:443/?timeout=30s: dial tcp 10.96.181.151:443: connect: connection refused
helm.go:94: [debug] Internal error occurred: failed calling webhook "validations.kong.konghq.com": Post https://test-kong-kong-validation-webhook.test-kong.svc:443/?timeout=30s: dial tcp 10.96.181.151:443: connect: connection refused
```

I don’t know if it’s because I started two kong charts in one cluster. 
I want to know why. And i want to know how to avoid it. thanks

**Comment by NICK-DUAN** [comment]
anybody help!

**Comment by hbagdi** [comment]
ping @rainest

**Comment by rainest** [comment]
It shouldn't be because there are multiple instances--the URLs are workspaced (that's what the `test-kong` before `svc` in `https://test-kong-kong-validation-webhook.test-kong.svc:443` is), and the only things that should be shared are the CRDs. Those may cause issues if you're trying to use different controller versions, but shouldn't affect communication with the webhook. Does it succeed if you only have one instance?

Do you see the same issue if you create that configuration bundle directly via kubectl? I don't really know much about Helm's behavior around checking custom resources against admission webhooks, which this appears to stem from.

Review of https://github.com/jetstack/cert-manager/issues/1425 suggests that this may be some scenario where old admission config somehow remains around, but again that's not something I'm particularly familiar with. Are the admission webhooks [enabled for either](https://github.com/Kong/charts/blob/master/charts/kong/values.yaml#L322-L325)? I'm not sure what's in those values.yamls.

**Comment by NICK-DUAN** [comment]
I already solved this problem, I user a annotation for `ingress`, `kongingress`, `kongplugin`, `kongconsumer`.
like this:
```yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: plugin-c
  annotaions:
    kubernetes.io/ingress.class: egress
```

we can change kong ingress.class in `values.yaml`.

values.yaml
```yaml
# some code
 ingressController:
  admissionWebhook:
    enabled: false
  ingressClass: egress
# some code 
```

And then you add route for this kong-ingress you should add the annotations:
```yaml
  annotaions:
    kubernetes.io/ingress.class: egress
```
