### ISSUE TITLE
annotations being mis-indented when added or overridden in --values

### ISSUE THREAD

**Issue by sanyer** [Kong/charts#199]
when annotations are included in --values, generated blocks look like this (have 4 spaces):
```yaml
annotations:
    konghq.com/protocol: "https"
    service.beta.kubernetes.io/azure-dns-label-name: "test-domain"
```
