### ISSUE TITLE
Error: in-memory storage can not be used when role = "control_plane" with postgres

### ISSUE THREAD

**Issue by charlie-haley** [Kong/charts#250]
I'm trying to deploy Kong in Hybrid mode using a slightly modified version of the [example values](https://github.com/Kong/charts/blob/main/charts/kong/example-values/minimal-kong-hybrid-control.yaml)

My data plane has come up succesfully along with the postgresdb, but my control plane is logging out the error `Error: in-memory storage can not be used when role = "control_plane"`
```
ingressController:
  enabled: false
  installCRDs: false
secretVolumes:
- kong-cluster-cert
env:
  database: 'off'
  role: control_plane
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
image:
  repository: kong
  tag: "2.2"
  pullPolicy: IfNotPresent
admin:
  enabled: true
  type: NodePort
  http:
    enabled: true
    servicePort: 8001
    containerPort: 8001
postgresql:
  enabled: true
  postgresqlUsername: kong
  postgresqlDatabase: kong
  service:
    port: 5432
cluster:
  enabled: true
  tls:
    enabled: true
    servicePort: 8005
    containerPort: 8005
proxy:
  enabled: false
nodeSelector:
  kubernetes.io/arch: amd64
serviceMonitor:
  enabled: true
  namespace: monitoring
```
