### ISSUE TITLE
Implement requests/limits for all containers

### ISSUE THREAD

**Issue by bugbuilder** [Kong/charts#264]
Hi there!

Kong chart have the possibility to define resource quotas for the main pods but don't have an option to inheritance this resource for the migration job and neither for the batch init container kong.wait-for-postgres. 

If we have a namespace with resourceQuotas, as example:

```
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: kong-rq-test
  namespace: kong
spec:
  hard:
    requests.cpu: '1'
    requests.memory: '2Gi'
    limits.cpu: '2'
    limits.memory: '4Gi'
```

When we try to install Kong in this environment, Kubernetes will be stuck int the migration-job:

`failed quota: kong-rq-test: must specify limits cpu,limits.memory,requests.cpu,requests.memory`

If  we inheritance the resources from the main container, this migrations will past but then we'll be stuck in the init continer.

Options:

1. Define limit range for the namespace, in this way all pod without resources defined will be use this default. Problems, what if the limit range defined is to minimal and the migrations job and batch pod cant run.
2. Inheritance the resource for migrations and define resources for batch.

Do you think that this issue needs to be resolved by the chart or is an administrator issue?

**Comment by mflendrich** [comment]
Thanks @bugbuilder for reporting this.

I think we should go with (2) because a global `LimitRange` wouldn't work well with multiple helm releases in the same namespace.
Updated the title to match (2).

**Comment by mflendrich** [comment]
@bugbuilder if you're willing to contribute a patch, that'd be greatly appreciated!

**Comment by bugbuilder** [comment]
@mflendrich sure, I'll work on this to day.

**Comment by bugbuilder** [comment]
@mflendrich sorry for the delay. I was thinking that a good approach to fix this, will be add a new set of resource limits, only for initcontainers and jobs, something  like this:

```
resourcesHelpers:
  waitFor:
    limits:
     cpu: 100m
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 256Mi
  migrations:
    limits:
     cpu: 100m
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 256Mi
```

In this way, we dont have to inheritance the resource from kong directly because they could be to agressive for productons enviroments and could be stuck a new upgrade. What do you think?
