### ISSUE TITLE
ServiceMonitor does not expose status port if proxy service is not enabled

### ISSUE THREAD

**Issue by slawekww** [Kong/charts#272]
Let's assume that kong helm chart is used to deploy Control Plane in hybrid mode without proxy service enabled.

Example helm values:

```yaml
deployment:
  kong:
    enabled: true

admin:
  enabled: true
cluster:
  enabled: true
proxy:
  enabled: false
ingressController:
  enabled: false
manager:
  enabled: true
portal:
  enabled: true
portalapi:
  enabled: true
clustertelemetry:
  enabled: true

serviceMonitor:
  enabled: true
```

It caused that status port is not exposed via kong k8s service, not labeled "enable-metrics: true"
and ServiceMonitor registered target in Prometheus but no endpoints are available.

Helm chart version: 1.14.3
