### ISSUE TITLE
Job does not work well with PDB (PodDistruptionBudget)

### ISSUE THREAD

**Issue by ttony** [Kong/charts#336]
Hi, 

currently, PDB selector is selecting as such:

```yaml
      app.kubernetes.io/instance: xxx
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kong
      app.kubernetes.io/version: "2.3"
      helm.sh/chart: kong-1.15.1
```

The labels above is also selecting job type pod such as migration job, etc... Job is not living pod as a result, PDB is not able to move it while let's say we are upgrading the worker nodes.

to fix this in we include 1 extra label at selector -- `app.kubernetes.io/component=app` in pdb.yaml:

```yaml
{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "kong.fullname" . }}
  namespace: {{ template "kong.namespace" . }}
  labels:
    {{- include "kong.metaLabels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end  }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end  }}
  selector:
    matchLabels:
      app.kubernetes.io/component: app
      {{- include "kong.metaLabels" . | nindent 6 }}
{{- end }}
```
