### ISSUE TITLE
kong still stuck on migrations update

### ISSUE THREAD

**Issue by Grounz** [Kong/charts#348]
Hi,

I have a kong deployed on Kubernetes cluster and i use remote postgresql database.

In the CICD i deploy with helm  a kong deployment. The deployment still stuck on init migrations phase in the kong pod and in the container `wait-for-db` i have this message:

```
  Run with --v (verbose) or --vv (debug) for more details
waiting for db
Error: /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:20: New migrations available; run 'kong migrations up' to proceed
```

I use 1.15.1 version of kong charts and i have use values.yml file:

```yaml
deployment:
  kong:
    enabled: true

env:
  database: "postgres"
  pg_user: "user"
  pg_password: "pass"
  pg_host: "host"
  pg_port: "5432"
  pg_database: "kong"

# Enable/disable migration jobs, and set annotations for them
migrations:
  # Enable pre-upgrade migrations (run "kong migrations up")
  preUpgrade: true
  # Enable post-upgrade migrations (run "kong migrations finish")
  postUpgrade: true

postgresql:
  enabled: false

...
```

What's the good parameter for run automatically  `kong migrations up` ?
