### ISSUE TITLE
KONG_HEADERS env var true/false boolean flag is invalid

### ISSUE THREAD

**Issue by MyMirelHub** [Kong/charts#356]
**Problem**
Setting an environment variable field to `off` in the helm chart, gets translated to `false` which is breaking the deployment. 

**What I expect to happen**
According to the configuration docs, boolean values of both `off` and `false` should be accepted and not beak the config. 

**Steps to reproduce**

In the chart `values.yaml`   I am setting the `HEADERS` field from `https://github.com/Kong/kong/blob/master/kong.conf.default` to `off`
  
```yaml
kong:
  env:  
      "HEADERS": "off"
```

The chart then translates this to `false` in the deployment which sends the pod in a crash loop

```yaml
      - env:
        - name: KONG_ADMIN_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_ADMIN_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_GUI_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_ADMIN_GUI_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_LISTEN
          value: 127.0.0.1:8444 http2 ssl
        - name: KONG_CLUSTER_LISTEN
          value: "off"
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_KIC
          value: "on"
        - name: KONG_HEADERS
          value: "false"
```
`kubectl get pods`
``` 
kong-release     1/3     CrashLoopBackOff   14         11m
```

**Additional details**

Editing the deployment yaml in k8s directly `kubectl edit kong.yaml` and setting it to `off` fixes it. 
```
- env:
        - name: KONG_HEADERS
          value: "off"
```

Kong chart version 2.1.0, 
Kong app version 2.4
