### ISSUE TITLE
Custom Container SecurityContext fields

### ISSUE THREAD

**Issue by ttony** [Kong/charts#373]
Hi,

I found that there is no place to include a security context in init-containers (wait-for-db) and containers. recently, our security scan tools pointed that such securityContext is mandatory:

```yaml
securityContext:
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
```

Currently, kong-helm supported securityContext for kong pods. for this request, we can use containers.securityContext? let me know if what's the suitable name for this.
