### ISSUE TITLE
Ingress template - Openshift 4.x support

### ISSUE THREAD

**Issue by ludovic-pourrat** [Kong/charts#374]
When deploying on Openshift, the current Ingress templating, does not allow to use the TLS termination to `passthrough`, because the path must not be set to the ingress.

Expected setup

```
    ingress:
      enabled: true
      hostname: my host-name
      annotations:
        route.openshift.io/termination: passthrough
      path: ""
```

See https://docs.openshift.com/container-platform/4.7/networking/routes/secured-routes.html

**Comment by ludovic-pourrat** [comment]
Purpose review of the Ingress templating.

```
  rules:
  - host: {{ $hostname }}
    http:
      paths:
        - backend:
            serviceName: {{ .fullName }}-{{ .serviceName }}
            servicePort: {{ $servicePort }}
          {{- if $path }}
          path: {{ $path }}
          {{- end -}}
  {{- if (hasKey .ingress "tls") }}
  tls:
  - hosts:
    - {{ $hostname }}
    secretName: {{ .ingress.tls }}
  {{- end -}}
```
