### ISSUE TITLE
Kong admission controller commonName lenght restriction

### ISSUE THREAD

**Issue by ludovic-pourrat** [Kong/charts#410]
Hi,

due to the DNS name length restriction the generated `commonName` for the Kong ingress controller validation webhook may exceed to allowance when the release name and the target namespace aren't short enough.

See

```
{{- define "kong.service.validationWebhook" -}}
{{ include "kong.fullname" . }}-validation-webhook
{{- end -}}
```

Would a feature to override the generated name will be accepted ?

I can provide a contribution via a PR proposal if accepted.

Advice ?

Thanks.

**Comment by rainest** [comment]
That or [truncating it](https://masterminds.github.io/sprig/strings.html#substr) would be fine, yes. Truncating could potentially result in collisions, but those should be unlikely, and worst case you need to choose a different release name to avoid it.

To override, I'd suggest:

```
  admissionWebhook:
    enabled: false
    # Optionally set a name for the webhook service and certificate.
    # This is only necessary if you see an "ERROR_TEXT" error indicating the default name is too long
    # name: whatever
    failurePolicy: Fail
```
and then having `kong.service.validationWebhook` return `ingressController.admissionWebhook.name` if set, or the current generated value otherwise.
