### ISSUE TITLE
Pass custom environmental variables into Kong ingress controller

### ISSUE THREAD

**Issue by MatteoInfi** [Kong/charts#411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

So, I need to pass extra env variable to my custom plugin.
In docker compose I just do this:

```
- DATABASE_HOST=myhost
- DATABASE_PASSWORD=123
- DATABASE_USER=root
- DATABASE_NAME=kong
- "KONG_NGINX_MAIN_ENV=DATABASE_HOST; env DATABASE_PASSWORD; env DATABASE_USER; env DATABASE_NAME"
```

This is working fine, however I don't know how to do the same with the Kong ingress controller, according to the chart value description:

> Specify Kong configuration
This chart takes all entries defined under `.env` and transforms them into into `KONG_*`
environment variables for Kong containers.
Their names here should match the names used in https://github.com/Kong/kong/blob/master/kong.conf.default
See https://docs.konghq.com/latest/configuration also for additional details

```
  env:
    log_level: info
    my_custom_var: hello
```

So if I put my custom variable there it will be transformed into `KONG_MY_CUSTOM_VAR`

So how can I do it? I cannot find where the Kong chart exposes additional environmental variables for the proxy pod

## Possible solutions
Just rename the variables this way:

```
- KONG_DATABASE_HOST=myhost
- KONG_DATABASE_PASSWORD=123
- "KONG_NGINX_MAIN_ENV=KONG_DATABASE_HOST; env KONG_DATABASE_PASSWORD"
```

---

Or override Kong deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-kong
  namespace: kong
spec:
  template:
    spec:
      containers:
      - name: proxy
        env:
        - name: DATABASE_HOST
          value: myhost
```

Is there a better way to do this?

Thanks
