### ISSUE TITLE
Pod failing to start if using custom image

### ISSUE THREAD

**Issue by MatteoInfi** [Kong/charts#417]
I am trying to use this chart with a custom image.

The image just contains the binary of my custom plugin, since it is a bit tricky to add them via configmap:

```
FROM golang:1.13-alpine AS builder

COPY plugin/go.mod /app/go.mod
WORKDIR /app
RUN go mod download
RUN go build main.go

FROM kong/kong-gateway:2.4.1.0-alpine

COPY --from=builder /app/myplugin /usr/local/bin/myplugin

```

my values.yaml:

```
kong:
  env:
    log_level: info
  image:
    repository: 000000000.dkr.ecr.region.amazonaws.com/myrepo
    tag: "891331798" // <= I use random tag to force helm deployments
    pullPolicy: Always

  proxy:
    annotations:
      "service.beta.kubernetes.io/aws-load-balancer-ssl-cert": "certificates arn"
      "service.beta.kubernetes.io/aws-load-balancer-type": "nlb"
      "service.beta.kubernetes.io/aws-load-balancer-ssl-ports": "kong-tls-proxy"
      "service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "tls"
      "service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled": "true"
```

Chart version: 

```
dependencies:
- name: kong
  repository: https://charts.konghq.com
  version: 2.2.0
digest: sha256:87f9ddce69f72e888e347db7a40b09fc5a01c561e50a10ab86e442e16b5ab1e4
generated: "2021-07-15T12:56:15.826055426+07:00"
```

Note:

- If I do not use the image the setup run without problems
- the image itself start without any issues
- I am using the same image with docker-compose without any issues

Errors:

```
Liveness probe failed: Get "http://192.168.11.3:8100/status": dial tcp 192.168.11.3:8100: connect: connection refused
Readiness probe failed: Get "http://192.168.11.3:10254/healthz": dial tcp 192.168.11.3:10254: connect: connection refused
```

or

```
Exec lifecycle hook ([/bin/sh -c /bin/sleep 15 && kong quit]) for Container "proxy" in Pod "podname_default(some uuid)" failed - error: command '/bin/sh -c /bin/sleep 15 && kong quit' exited with 127: /bin/sh: 1: kong: not found , message: "/bin/sh: 1: kong: not found\n"

```

What could be the cause?

Thanks

----

Since I am here I would like to bring another issue I am having.
This configuration: 

```
  proxy:
    annotations:
      "service.beta.kubernetes.io/aws-load-balancer-ssl-cert": "certificates arn"
      "service.beta.kubernetes.io/aws-load-balancer-type": "nlb"
      "service.beta.kubernetes.io/aws-load-balancer-ssl-ports": "kong-tls-proxy"
      "service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "tls"
      "service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled": "true"
```

Will start an AWS NLB, however it does not configure the TLS certificate correctly, I have to do it manually, same it happens for the ELB, what am I doing wrong?
