### ISSUE TITLE
Unable to find a working sample for the Minikube

### ISSUE THREAD

**Issue by dzmitry-kankalovich** [Kong/charts#431]
Hello all,

I've stuck with trying to build a working sample of Kong Gateway on top of `minikube` with this chart. The documentation is extremely confusing and, as I suspect, is outdated.

So the context: I need to evaluate the **mTLS** plugin which is available only with Kong Konnect subscription (aka Enterprise edition). As I understand, I can evaluate it with a minimal setup which is [DB-less with Kong Ingress Controller](https://docs.konghq.com/enterprise/2.5.x/deployment/installation/kong-for-kubernetes/) using CRD resources to create sample routes and mTLS plugin.

So I went with creating a trial account and provisioning the Runtime. Per documentation [here](https://docs.konghq.com/konnect/runtime-manager/gateway-runtime-kubernetes/) I went with **Helm 3** and the following `values.yaml` (exactly as it was auto-generated on the Runtime page)

```yaml
image:
  repository: kong/kong-gateway
  tag: "2.4.1.1-alpine"

secretVolumes:
  - kong-cluster-cert
  - kong-cluster-ca

env:
  role: data_plane
  database: "off"
  anonymous_reports: off
  vitals_ttl_days: 732
  cluster_mtls: pki
  cluster_control_plane: <redacted>:443
  cluster_server_name: <redacted>
  cluster_telemetry_endpoint: <redacted>:443
  cluster_telemetry_server_name: <redacted>
  cluster_ca_cert: /etc/secrets/kong-cluster-ca/ca.crt
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  lua_ssl_trusted_certificate: /etc/secrets/kong-cluster-ca/ca.crt

ingressController:
  enabled: false
  installCRDs: false
```
combining this with `minikube tunnel` I can get the response from the gateway:
```bash
$ curl http://127.0.0.1/echo
{"message":"no Route matched with those values"}
```

And here is where I am absolutely lost - how do you configure route mapping once the deployment is done? Absolutely nothing in the documentation works:
- There is no way to use `decK` since Admin API is not exposed, and anyway it's not clear if you can use it in `DB-less` mode
- The CRD way with `KongIngress` does not seem to work at all - may be related to the `ingressController.enabled: false` line in the `values.yaml`? Then how do you suppose to configure routes?

I've tried:
- enable `ingressController` - it fails to start its container with liveness probe exceptions
- enable Admin API and expose it via Kong itself - it refuses connections
- tried following [these steps](https://docs.konghq.com/kubernetes-ingress-controller/1.3.x/guides/getting-started/) with no result - it seems outdated since it doesn't use annotations for configuration

So my question is really - where do I find a minimal **working** example with DB-less Kong for Kubernetes Enterprise on minikube with routes configuration?
