### ISSUE TITLE
udpProxy configuration uses TCP for listener

### ISSUE THREAD

**Issue by shaneutt** [Kong/charts#445]
While [working on documentation for 2.x](https://github.com/Kong/docs.konghq.com/pull/3121) and testing the `udpProxy` section of the Helm chart I found that the `KONG_STREAM_LISTEN` configuration can become broken.

The following is my `values.yaml`:

```yaml
ingressController:
  image:
    tag: "2.0.0-beta.2"
udpProxy:
  enabled: true
  type: LoadBalancer
  stream:
  - containerPort: 9999
    servicePort: 9999
    protocol: UDP
```

Given the above `values.yaml` the `KONG_STREAM_LISTEN` environment variable that was produced for the Kong proxy pods was:

```yaml
- name: KONG_STREAM_LISTEN
  value: 0.0.0.0:9999
```

This lead to my `UDPIngress` resources being inoperable, as it seems the default of `TCP` will be used if the protocol isn't specified here.

I was able to work around this by manually patching the pods with the following values:

```yaml
- name: KONG_STREAM_LISTEN
  value: "0.0.0.0:9999 udp"
```

After that change my `UDPIngress` resources started to route traffic properly.
