### ISSUE TITLE
How to install and configure community plugins like acme

### ISSUE THREAD

**Issue by djakielski** [Kong/charts#453]
Hi,

i want to use [acme plugin](https://docs.konghq.com/hub/kong-inc/acme/) without manuel installation of this plugin. How can i do this? Is there any option to create an crd for plugin within the chart installation?

I see this crd to install it. But i want it directly with the install and not in a seperate (manuel) step.

```yaml
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: <global-acme>
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: \"true\"
config: 
  account_email: example@example.com
plugin: acme
```

Any ideas?
