### ISSUE TITLE
Custom plugin load

### ISSUE THREAD

**Issue by tsn77130** [Kong/charts#460]
Trying to load custom jwt2header plugin with helm config, I've created configmap as detailled in README with
`kubectl create configmap -n kong kong-jwt2header --from-file=jwt2header`

Then Added config in values.yml

```
plugins:
  configMaps:
  - pluginName: jwt2header
    name: kong-jwt2header

```

When adding kong cluster plugin, I've got errors logs in proxy container

```
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-jwt2header
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config:
  strip_claims: "false"
  token_required: "true"
plugin: kong-jwt2header
```

Logs:
```
my-kong-kong-wgqpl:ingress-controller time="2021-09-23T08:19:34Z" level=error msg="failed to sync: posting new config to /config: HTTP status 400 (message: \"declarative config is invalid: {plugins={[3]={name= 
 \\\"plugin 'kong-jwt2header' not enabled; add it to the 'plugins' configuration property\\\"}}}\")" component=sync-queue
```

Helm chart version : kong-2.3.0
App version : 2.5
