### ISSUE TITLE
kong-2.6.0 chart clear-stale-pid init-container does not respect imagePullPolicy

### ISSUE THREAD

**Issue by jbeaken** [Kong/charts#495]
With helm chart 2.6, there is a new init container 
```yaml
     initContainers:
      - name: clear-stale-pid
        image: kong:latest`
```

This sits next to the previous existing **wait-for-db** init container. But unlike wait-for-db, clear-stale-pid does not respect **imagePullPolicy** from the helm values. 

This causes problems for us deploying locally (minikube) as we used latest tag which has default **imagePullPolicy** of **Always**, so minikube was always looking for an external repo.

QucikFix is not to use latest tag, thereby changing default imagePullPolicy to *IfNotPresent*
