### ISSUE TITLE
Unexpected result for standalone controller node

### ISSUE THREAD

**Issue by kroonprins** [Kong/charts#546]
Hello,
I am trying to follow the instructions as given here in the documentation: https://github.com/Kong/charts/blob/main/charts/kong/README.md#standalone-controller-nodes.

The values.yaml file that I have is the following for testing:

```yaml
image:
  # Kong Enterprise
  repository: kong/kong-gateway
  tag: "2.7.1.1-alpine"

namespace: kong

replicaCount: 2

env:
  role: control_plane
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  admin_api_uri: http://control-plane-kong-admin.kong.svc:8001
  password:
    valueFrom:
      secretKeyRef:
        name: kong-enterprise-superuser-password
        key: password

secretVolumes:
  - kong-cluster-cert

ingressController:
  env:
    ingressClass: myworkspace
    admin_filter_tag: myworkspace
    kong_workspace: myworkspace
    kong_admin_url: http://control-plane-kong-admin.kong.svc:8001
    publish_service: kong/data-plane-kong-proxy
    kong_admin_token:
      valueFrom:
        secretKeyRef:
          name: kong-enterprise-superuser-password
          key: password
  enabled: true
  installCRDs: false

proxy:
  enabled: false

admin:
  enabled: false

manager:
  enabled: false

portal:
  enabled: false

portalapi:
  enabled: false

migrations:
  preUpgrade: false
  postUpgrade: false

deployment:
  test:
    enabled: false
  kong:
      enabled: false

enterprise:
  enabled: true
  license_secret: kong-enterprise-license
```

If I use this, then there is some output that I did not immediately expect:

- In the `Deployment` on the `ingress-controller` container, in the `env` there is this:

```yaml
        - name: CONTROLLER_INGRESSCLASS
          value: "myworkspace"
        - name: CONTROLLER_INGRESS_CLASS
          value: "kong"
```

Seems like this should have been?

```yaml
        - name: CONTROLLER_INGRESS_CLASS
          value: "myworkspace"
```

- In the definition of the `Role` there is this:

```yaml
    resourceNames:
      # Defaults to "<election-id>-<ingress-class>"
      # Here: "<kong-ingress-controller-leader-nginx>-<nginx>"
      # This has to be adapted if you change either parameter
      # when launching the nginx-ingress-controller.
      - "kong-ingress-controller-leader-kong-kong"
```
and correspondingly in the `env` on the `ingress-controller` container in the `Deployment` :

```yaml
        - name: CONTROLLER_ELECTION_ID
          value: "kong-ingress-controller-leader-kong"
```

Should this not be `kong-ingress-controller-leader-myworkspace`?
