### ISSUE TITLE
Allow wildcards in ingress hostnames

### ISSUE THREAD

**Issue by MaroonedMind** [Kong/charts#579]
Kong helm chart version: 2.7.0

Kong helm chart rendering fails when using a wildcard in a hostname (e.g. "*.foo.com").
The following error is shown: 

> Error: YAML parse error on chart-kong/charts/data-plane/templates/service-kong-proxy.yaml: error converting YAML to JSON: yaml: line 22: did not find expected alphabetic or numeric character

This may be fixed by changing the line 68 in _helpers.tpl to pass the string value to the quote function:
`{{- $hostname := .ingress.hostname | quote -}}`

Steps to reproduce:
1.  Configure Proxy ingress object to use wildcard hostname in the `values.yaml` file
```
 proxy:
    enabled: true
    type: ClusterIP
    ingress:
      enabled: true
      hostname: "*.api.com"
```
2. Run the `helm template` command
