### ISSUE TITLE
Cannot configure admin/manager hostname from kubernetes secrets/config maps

### ISSUE THREAD

**Issue by moconno** [Kong/charts#58]
Hi,

I have my admin/manager values .yaml configured like so: 

```yaml
admin:
        useTLS: false	        
        enabled: true	     
        type: NodePort	
        ingress:
            enabled: true	
            hostname: 
                valueFrom:
                    secretKeyRef:
                        name: kong-admin-hostname
                        key: hostname

    manager:
        tls: 
            enabled: false
        type: NodePort
        ingress:
            enabled: true
            hostname: 
                valueFrom:
                    secretKeyRef:
                        name: kong-manager-hostname
                        key: hostname
```

I'm receiving this error when deploying kong. 

coalesce.go:199: warning: destination for hostname is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for hostname is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for hostname is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for hostname is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for hostname is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for hostname is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for hostname is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for hostname is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for hostname is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for hostname is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for hostname is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for hostname is a table. Ignoring non-table value <nil>
Error: YAML parse error on w2g-kong/charts/kong/templates/migrations-post-upgrade.yaml: error converting YAML to JSON: yaml: line 82: could not find expected ':'
helm.go:76: [debug] error converting YAML to JSON: yaml: line 82: could not find expected ':'

It appears the helm chart is having trouble parsing the hostname value.  I was able to confirm this by hardcoding the hostname value and the chart deployed successfully.
