### ISSUE TITLE
proxy cannot autoconnect to the postgrasql database

### ISSUE THREAD

**Issue by Pancongwen** [Kong/charts#590]
chart version: 2.8.0

```yaml
# values.yaml
namespace: kong
postgresql:
  enabled: true
ingressController:
  enabled: true
admin:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false
proxy:
  enabled: true
  http:
    enabled: true
  labels:
    enable-metrics: "true"
serviceMonitor:
  enabled: true
  namespace: kong
```

After installation, the postgresql, proxy and controller starts correctly. But when i try to add a service:
```bash
$ curl -i -X POST --url http://IP:PORT/services/ --data 'name=example-service' --data 'url=http://mockbin.org'
HTTP/1.1 405 Not Allowed
Date: Thu, 05 May 2022 11:00:18 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Access-Control-Allow-Origin: *
Content-Length: 114
X-Kong-Admin-Latency: 1
Server: kong/2.8.1

{"name":"operation unsupported","code":12,"message":"cannot create 'services' entities when not using a database"}
```
