### ISSUE TITLE
Test jobs are always created in the default namespace

### ISSUE THREAD

**Issue by dlouzan** [Kong/charts#605]
Hello, this might be a misconfiguration on my end, though I have tried multiple configuration options to no avail. Anytime I deploy the helm chart, I get some test jobs on the default namespace, even though I want and set this to be on a fixed `kong` namespace (the default namespace is also used, but for other tasks):

Sample `values.yml`:

```yaml
namespace: kong
```

Sample CLI call:

```sh
helm template kong/kong --namespace kong --values ./values.yml --version=2.8.2
```

In the output, everything is namespaced except these three pods:

```yaml
# Source: kong/templates/tests/test-jobs.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "release-name-test-ingress"
  annotations:
    "helm.sh/hook": test
spec:
  restartPolicy: OnFailure
  containers:
    - name: "release-name-curl"
      image: curlimages/curl
      command:
        - curl
        - "http://release-name-kong-proxy.kong.svc.cluster.local/httpbin"
---
# Source: kong/templates/tests/test-jobs.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "release-name-test-ingress-v1beta1"
  annotations:
    "helm.sh/hook": test
spec:
  restartPolicy: OnFailure
  containers:
    - name: "release-name-curl"
      image: curlimages/curl
      command:
        - curl
        - "http://release-name-kong-proxy.kong.svc.cluster.local/httpbin-v1beta1"
---
# Source: kong/templates/tests/test-jobs.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "release-name-test-httproute"
  annotations:
    "helm.sh/hook": test
spec:
  restartPolicy: OnFailure
  containers:
    - name: "release-name-curl"
      image: curlimages/curl
      command:
        - curl
        - "http://release-name-kong-proxy.kong.svc.cluster.local/httpbin-httproute"
```

This is kind-of related to https://github.com/Kong/charts/pull/599, but in principle I'd like to keep the tests, just that they should respect the namespace setting 😅 

It is not a huge issue, it just contaminates a bit the default namespace, since I wanted to keep everything ingress-related into the `kong` namespace.

Thanks for the awesome work!
