### ISSUE TITLE
Ingress capabilities detection

### ISSUE THREAD

**Issue by ludovic-pourrat** [Kong/charts#616]
Hi,

Since we upgraded our Kubernetes cluster we identified that the `kong.ingressVersion` helper function is not applying the right capabilities detection switch.

We are automatically detecting capabilities on our cluster and passing those to the Helm templating via `kubectl api-versions`

Current implementation defines

```
{{- define "kong.ingressVersion" -}}
{{- if (.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress") -}}
networking.k8s.io/v1
{{- else if (.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress") -}}
networking.k8s.io/v1beta1
{{- else -}}
extensions/v1beta1
{{- end -}}
{{- end -}}
```

Where it should be 

```
{{- define "kong.ingressVersion" -}}
{{- if (.Capabilities.APIVersions.Has "networking.k8s.io/v1") -}}
networking.k8s.io/v1
{{- else if (.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1") -}}
networking.k8s.io/v1beta1
{{- else -}}
extensions/v1beta1
{{- end -}}
{{- end -}}
```

Are our assumptions correct ?

If so I will raise a PR for this.

Many thanks.

**Comment by pmalek** [comment]
Hi @ludovic-pourrat 👋 

It seems you're right. Given this handy template:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: apiversions-{{ .Release.Name }}
  namespace: apiversions
data:
  apiVersions.txt: |
    {{- range .Capabilities.APIVersions }}
    - {{ . }}
    {{- end -}}
```

I can confirm I'm getting the api versions as you've indicated:

```yaml
---
# Source: kong/templates/cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: apiversions-kong-test1
  namespace: apiversions
data:
  apiVersions.txt: |
    - v1
    - admissionregistration.k8s.io/v1
    - admissionregistration.k8s.io/v1beta1
    - internal.apiserver.k8s.io/v1alpha1
    - apps/v1
    - apps/v1beta1
    - apps/v1beta2
    - authentication.k8s.io/v1
    - authentication.k8s.io/v1beta1
    - authorization.k8s.io/v1
    - authorization.k8s.io/v1beta1
    - autoscaling/v1
    - autoscaling/v2
    - autoscaling/v2beta1
    - autoscaling/v2beta2
    - batch/v1
    - batch/v1beta1
    - certificates.k8s.io/v1
    - certificates.k8s.io/v1beta1
    - coordination.k8s.io/v1beta1
    - coordination.k8s.io/v1
    - discovery.k8s.io/v1
    - discovery.k8s.io/v1beta1
    - events.k8s.io/v1
    - events.k8s.io/v1beta1
    - extensions/v1beta1
    - flowcontrol.apiserver.k8s.io/v1alpha1
    - flowcontrol.apiserver.k8s.io/v1beta1
    - flowcontrol.apiserver.k8s.io/v1beta2
    - networking.k8s.io/v1
    - networking.k8s.io/v1beta1
    - node.k8s.io/v1
    - node.k8s.io/v1alpha1
    - node.k8s.io/v1beta1
    - policy/v1
    - policy/v1beta1
    - rbac.authorization.k8s.io/v1
    - rbac.authorization.k8s.io/v1beta1
    - rbac.authorization.k8s.io/v1alpha1
    - scheduling.k8s.io/v1alpha1
    - scheduling.k8s.io/v1beta1
    - scheduling.k8s.io/v1
    - storage.k8s.io/v1beta1
    - storage.k8s.io/v1
    - storage.k8s.io/v1alpha1
    - apiextensions.k8s.io/v1beta1
    - apiextensions.k8s.io/v1
```

Feel free to submit a fix for that.
