### ISSUE TITLE
Helm Chart Breaks Deployment in Kuma

### ISSUE THREAD

**Issue by doctorwu** [Kong/charts#620]
With the latest version of Helm chart (2.10), deploying KIC when Kuma fails. It is related to this PR, #619 

We need a way to manually mount. The proposed solution from mesh team is to use a ContainerPatch. Use the following as a guide:

```
apiVersion: kuma.io/v1alpha1
kind: ContainerPatch
metadata:
  name: container-patch-kong-token
  namespace: kong-mesh-system
spec:
  sidecarPatch:
    - op: add
      path: /volumeMounts/-
      value: '{ "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount/token", "name":"kong-1656434665-kong-token", "readOnly": "true", "subPath": "token" }'
    - op: add
      path: /volumeMounts/-
      value: '{ "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt", "name":"kong-1656434665-kong-token", "readOnly": "true", "subPath": "ca.crt" }'
    - op: add
      path: /volumeMounts/-
      value: '{ "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount/namespace", "name":"podinfo", "readOnly": "true", "subPath": "namespace" }'
```

Could have a `kuma: enabled` flag or something to trigger the creation of ContainerPatch.

## Prerequisites

- [ ] https://github.com/Kong/kubernetes-testing-framework/issues/303
