### ISSUE TITLE
How to deploy Kong as separate deployments(proxy, manager and admin)

### ISSUE THREAD

**Issue by srreddy2020** [Kong/charts#676]
Hello Team,
We are deploying kong through Helm approach. While Deployed Kong, we can see all the components are in single deployment like  "deployment.apps/kong-kong", 
But our requirement is to have separate deployments for Proxy,manager and admin?
Please suggest how can we deploy the same.

**Comment by ludovic-pourrat** [comment]
Hi, we are achieving this pattern with an umbrella chart that instantiate the Kong helm chart for each component we need, aka the proxy, the manager and the ingress controller.

```yaml
dependencies:
  - name: helm-kong
    repository: ...
    alias: kcp
  - name: helm-kong
    repository: ...
    alias: kdp
  - name: helm-kong
    repository: ...
    alias: kic
```

Ludovic.
