### ISSUE TITLE
Issue while setting up connection with postgres RDS (AWS Aurora )

### ISSUE THREAD

**Issue by last-warrior** [Kong/charts#693]
Hi All, 
I am trying to deploy kong gateway using helm charts. 
When helm is trying to run the migrations, I am getting following error.

```
Error: [PostgreSQL error] cluster_mutex callback threw an error: /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:95: Database is older than Kong Enterprise 1.5.0.

To migrate from a version older than Enterprise 1.5.0, migrate to Kong Enterprise 1.5.0 first.

To migrate from Kong Community Edition, versions should be the same
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:95: in function </usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:87>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/db/init.lua:409: in function </usr/local/share/lua/5.1/kong/db/init.lua:359>
	[C]: in function 'pcall'
	/usr/local/share/lua/5.1/kong/concurrency.lua:52: in function 'cluster_mutex'
	/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:87: in function 'up'
	/usr/local/share/lua/5.1/kong/cmd/migrations.lua:341: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:97: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:97>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:97: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:54>
	/usr/local/bin/kong:9: in function 'file_gen'
	init_worker_by_lua:47: in function <init_worker_by_lua:45>
	[C]: in function 'xpcall'
	init_worker_by_lua:54: in function <init_worker_by_lua:52>

  Run with --v (verbose) or --vv (debug) for more details
```

can someone help here ?

**Comment by pmalek** [comment]
Hi @gargAdityaZepto 👋 

What version of chart are you using? Can you attach the `values.yaml` that you used to deploy?

Are you upgrading an existing installation? The error message would indicate so 🤔 

```
Database is older than Kong Enterprise 1.5.0.

To migrate from a version older than Enterprise 1.5.0, migrate to Kong Enterprise 1.5.0 first.

To migrate from Kong Community Edition, versions should be the same
```

**Comment by last-warrior** [comment]
Hi @pmalek ,

I am doing a new deployment for gateway!
chart version: 2.13.1
app version: 3.0

values.yml
```
env:
  database: "postgres"
  pg_host: "<host>"
  pg_port: "5432"
  pg_user: "postgres"
  pg_password: "<password>"
  pluginserver_validate_session_socket: "/usr/local/bin/validate-session.socket"
  pluginserver_validate_session_start_cmd: "/usr/local/bin/validate-session"
  pluginserver_validate_session_query_cmd: "/usr/local/bin/validate-session -dump"
  plugins: "bundled,validate-session"
  log_level: "debug"


admin:
  enabled: true
  http:
    enabled: true

image:
  repository: kong
  tag: "latest"
ingressController:
  installCRDs: false
```
