### ISSUE TITLE
Custom ingressClass resource didn't create

### ISSUE THREAD

**Issue by falsedlah** [Kong/charts#698]
Use case: 

Two charts deployment:
      1. `kong` with the default setting 
      2. `kong-internal`: with `IngressClass: kong-internal`
```
...
ingressController:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
      ingressClass:  kong-internal
...
```
When I check the ingress class 
```
#kubectl get ingressclass -A

NAME   CONTROLLER                      PARAMETERS   AGE
alb    ingress.k8s.aws/alb             <none>       44d
kong   konghq.com/ingress-controller   <none>       252d
```

Expected: 
I expected to see two Kong ingressClass but I see only one which the default and I didn't see the custom one that I created
