### ISSUE TITLE
Setting Kong Proxy to use an existing Load Balancer

### ISSUE THREAD

**Issue by carmine-ianniello-deltatre** [Kong/charts#743]
Hello, 

Maybe I'm a bit lost in the documentation but seems impossible to set the kong proxy to use an existing load balancer.
Let's say I have an aws eks cluster, with a load balancer.
How can I set the proxy in order to let it use the already created one? 
Is there any flag, any annotation to use? 
I also tried to specify this annotation service.beta.kubernetes.io/aws-load-balancer-internal: true, but with no luck.

```yaml
proxy:
  enabled: true
  type: LoadBalancer
  annotations: {  service.beta.kubernetes.io/aws-load-balancer-internal: true   }
```

Funny thing is that in the yaml manifest instead, it's possible to set (at least) the LoadBalancerIP.

```yaml
kind: Service
metadata:
  annotations: {}
  name: kong-proxy
  namespace: kong
spec:
  ports:
  - name: proxy
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: proxy-ssl
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: ingress-kong
  type: LoadBalancer
  loadBalancerIP: 20.229.110.105
```

Any suggestion will be really appreciated.

Thanks!

**Comment by pmalek** [comment]
Hello @CarmineDeloitte 👋 

By LoadBalancer do you mean AWS' ELB/ALB/NLB? Or do you have an existing Service of type `LoadBalancer`? If it's the latter then you should be able to just point it to kong's deployment via the label selectors.

If it's the former than I'm not sure. It seems that you can use a `TargetGroupBinding ` CRD for ALB use case: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/targetgroupbinding/targetgroupbinding/

**Comment by carmine-ianniello-deltatre** [comment]
Hello @pmalek 

Yep I have an ELB load balancer in AWS, but how can I use the TargetGroupBinding ?
Just as a labels selector in the kong chart?

**Comment by pmalek** [comment]
Hm to be honest, I'm not sure. From what I can read at https://github.com/kubernetes-sigs/aws-load-balancer-controller it seems that it works with ALB and NLB.

Which type of a LB specifically are you having?

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/739996/218984912-a5af1e4e-333b-443f-8efd-c001b1726edb.png">

ELB in AWS is a generic term, no? I believe you should be able to use the `TargetGroupBinding` as denoted in [their docs](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/targetgroupbinding/targetgroupbinding/):

```yaml
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: my-tgb
spec:
  serviceRef:
    name: awesome-service # route traffic to the awesome-service
    port: 80
  targetGroupARN: <arn-to-targetGroup>
```

If that's not the case, don't hesitate to reach us.
