### ISSUE TITLE
Enable all kube-linter rules

### ISSUE THREAD

**Issue by czeslavo** [Kong/charts#753]
## Context

In https://github.com/Kong/charts/pull/751 we added kube-linter to our CI pipeline, suppressing all rules that were failing. The goal of this ticket is to enable all ignored rules OR add an explicit ignore annotation to the objects that have to break the rule due to some higher requirement.

The annotation can look as follows:
```yaml
metadata:
  annotations:
    ignore-check.kube-linter.io/privileged: "This deployment needs to run as privileged because it needs kernel access"
```

## Rules to be enabled 
- [x] "no-read-only-root-fs"
- [x] "run-as-non-root"
- [ ] "unset-cpu-requirements"
- [ ] "unset-memory-requirements"

## Acceptance criteria
- [ ] No rules are specified in the `exclude` section of the `.kube-linter.yaml` config. 
- [ ] If there was an object in the helm chart that has to break any of the rules, it's explicitly explained in form of an `ignore-check.kube-linter.io/rule-name` annotation
