### ISSUE TITLE
Utilizing vault to manage secrets with kong - ingest conf file

### ISSUE THREAD

**Issue by jeremiahbowen** [Kong/charts#771]
We are utilizing the following annotations on the kong deployment:
```yaml
podAnnotations:
  vault.hashicorp.com/agent-init-first: "true"
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-inject-secret-kong.conf: env-secrets/db-creds
  vault.hashicorp.com/agent-inject-template-kong.conf: |-
    {{ with secret "env-secrets/data/db-creds" -}}
    database    = postgres
    pg_database = kong
    pg_user     = "{{ .Data.data.username }}"
    pg_password = "{{ .Data.data.password }}"
    pg_host     = "{{ .Data.data.host }}"
    {{- end }}
  vault.hashicorp.com/agent-inject-token: "false"
  vault.hashicorp.com/agent-pre-populate: "true"
  vault.hashicorp.com/agent-pre-populate-only: "true"
  vault.hashicorp.com/role: kong-role
  vault.hashicorp.com/secret-volume-path-kong.conf: /etc/kong
```
This creates the config file `/etc/kong/kong.conf` in the container, similar to the following:
```conf
database    = postgres
pg_database = kong
pg_user     = "kong"
pg_password = "redacted"
pg_host     = "pg.host.com"
```
We need the chart to allow kong to pick up a configured conf file.
Currently, the `wait-for-db` container errors with this message because it's not picking up that conf.
```
Error: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: host or service not provided, or not known
  Run with --v (verbose) or --vv (debug) for more details
waiting for db    
```
