### ISSUE TITLE
Is it possible to deploy AWS LB on an on-prem k8s cluster running in AWS

### ISSUE THREAD

**Issue by ben5556** [Kong/charts#934]
Is it possible to deploy AWS LB on an on-prem k8s cluster running in AWS.

Below is a snippet of my Kong yaml which I tried but the service shows external IP as <pending>. Doing a describe on the service shows no events. No events in the namespace as well. I am wondering since I am not running an EKS cluster, may be this isn't supported ? Any assistance here is greatly appreciated thanks

```
proxy:
  type: LoadBalancer
  enabled: true
  http:
    enabled: true
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "<>"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
ingressController:
  installCRDs: false

ֿenv:
  headers: "off"
  trusted_ips: 0.0.0.0/0,::0

```
